apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml

#namespace: argocd
#helmGlobals:
#  - name: cert-manager
#    repo: https://charts.jetstack.io
#    version: v1.5.3
#    releaseName: my-cert-manager
#    namespace: argocd
#  - secrets.yml
#  - deployment.yml
#  - ../base
#  - servi

#namePrefix: demo
#nameSuffix: yuri
