apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  secretName: certificate-ca-tls
  commonName: yurikrupnik.com
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  usages:
    - server auth
    - client auth
#  privateKey:
#    algorithm: ECDSA
#    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
#    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: certificate-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yurikrupnik-domain-server
  namespace: istio-system
spec:
  isCA: false
  secretName: wild-card-tls
  commonName: "*.yurikrupnik.com"
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.yurikrupnik.com"
  #  privateKey:
  #    algorithm: ECDSA
  #    size: 256
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
#    group: cert-manager.io
