#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: users-api-url
#data:
#  api_gateway_url: users-api-service
#  port: "3333"
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  labels:
    app: auth-app
spec:
  replicas: 1
  template:
    metadata:
      name: auth-app
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: yurikrupnik/auth-app:latest
          #          image: europe-west1-docker.pkg.dev/maya-mussia/nx-go-playground/auth-app:latest
          imagePullPolicy: IfNotPresent
#          volumeMounts:
#            - mountPath: /etc/nginx/conf.d
#              name: nginx-configs
          env: # not working only front end
            - name: VITE_API_HOST
              valueFrom:
                configMapKeyRef:
                  key: api_gateway_url
                  name: users-api-url
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: users-api-url
            - name: VITE_AR
              value: "aris shit"
#      volumes:
#        - name: nginx-config
#          configMap:
#            name: nginx-config
#        - name: nginx-configs
#          configMap:
#            name: nginx-configs
      #        - name: haproxy-config
      #          configMap:
      #            name: haproxy-config

      restartPolicy: Always
  selector:
    matchLabels:
      app: auth-app
