apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  labels:
    run: auth-app-service
    custom: my-custom-label-service-value
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: auth-app
