#kind: Cluster
#apiVersion: kind.x-k8s.io/v1alpha4
#nodes:
#  - role: control-plane
#  - role: worker
#  - role: worker
#  - role: worker
#---
#apiVersion: ctlptl.dev/v1alpha1
#kind: Cluster
#product: kind
#nodes:
#  - role: control-plane
#  - role: worker
#  - role: worker
#registry: ctlptl-registry
#---
#apiVersion: ctlptl.dev/v1alpha1
#kind: Registry
#name: ctlptl-registry
#port: 5005
