---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
#          image: bitnami/kubectl:1.22.15
          image: alpine/helm
#          command: ["kubectl", "get", "pods", "-A"]
          command: ["helm", "help"]
#          volumeMounts:
#            - mountPath: /etc/kubectl/config
#              name: kube-config
#      volumes:
#        - name: kube-config
#          configMap:
#            name: kube-config
      restartPolicy: Never
  backoffLimit: 4
