apiVersion: v1
kind: Service
metadata:
  name: controller1-service
  labels:
    run: controller1-service
spec:
  type: ClusterIP
  ports:
    - port: 3008
      protocol: TCP
      targetPort: 8080
  selector:
    app: controller1
