apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example
  namespace: example-ns
spec:
  provider:
      gcpsm:
      # Auth defines the information necessary to authenticate against GCP by getting
      # the credentials from an already created Kubernetes Secret.
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: MONGO_URI
            key: MONGO_URI
            # namespace: asd
      projectID: maya-mussia


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: 
  name: example
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: example
    kind: SecretStore
  target:
    name: my-secret
    creationPolicy: Owner
  data:
  - secretKey: demo-key
    remoteRef:
      key: demo-secret
  # dataFrom:
  #   - extract:
  #     key: a-team-mongodb
