---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: iol
  iopsPerGB: '10'
  fsType: ext4
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: my-pvc
##  namespace: foo
#spec:
#  #  resources:
#  #    requests:
#  #      storage: 5Gi
#  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
#  volumeName: slow
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: slow
#  labels:
#    failure-domain.beta.kubernetes.io/zone: us-central1-a__us-central1-b
#spec:
#  #  storageClassName: ""
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 10Gi
#  gcePersistentDisk:
#    pdName: my-data-disk
#    fsType: ext4
##  claimRef:
#    name: foo-pvc
#    namespace: storage
#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: fast
#provisioner: kubernetes.io/glusterfs
#parameters:
#  resturl: "http://192.168.10.100:8080"
#  restuser: ""
#  secretNamespace: ""
#  secretName: ""


#allowVolumeExpansion: true
