[package]
name = "projects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
log = "0.4.17"
mongodb = "2.3.0"
serde = "1.0.143"
tokio = "1.20.1"
